<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-20T14:48:02 IST" name="Suite" finished-at="2023-12-20T14:48:29 IST" duration-ms="26815">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorHandlingTest.LoginErrorValidation()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" name="LoginErrorValidation" class="shravang.Tests.ErrorHandlingTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="StandAloneTest.submitOrder(java.util.HashMap)[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" name="submitOrder" class="shravang.Tests.StandAloneTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-12-20T14:48:02 IST" name="Error Handling Test" finished-at="2023-12-20T14:48:27 IST" duration-ms="25162">
      <class name="shravang.Tests.ErrorHandlingTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" started-at="2023-12-20T14:48:02 IST" name="launchApplication" finished-at="2023-12-20T14:48:13 IST" duration-ms="11394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" started-at="2023-12-20T14:48:13 IST" name="LoginErrorValidation" finished-at="2023-12-20T14:48:14 IST" duration-ms="711" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" started-at="2023-12-20T14:48:14 IST" name="tearDown" finished-at="2023-12-20T14:48:16 IST" duration-ms="1602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" started-at="2023-12-20T14:48:16 IST" name="launchApplication" finished-at="2023-12-20T14:48:25 IST" duration-ms="8811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" started-at="2023-12-20T14:48:25 IST" name="ProductErrorValidation" finished-at="2023-12-20T14:48:25 IST" duration-ms="660" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "product" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "product" is null
at shravang.pageobjects.ProductCatalog.addProductToCart(ProductCatalog.java:58)
at shravang.Tests.ErrorHandlingTest.ProductErrorValidation(ErrorHandlingTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shravang.Tests.ErrorHandlingTest@117159c0]" started-at="2023-12-20T14:48:26 IST" name="tearDown" finished-at="2023-12-20T14:48:27 IST" duration-ms="1460" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- shravang.Tests.ErrorHandlingTest -->
    </test> <!-- Error Handling Test -->
    <test started-at="2023-12-20T14:48:02 IST" name="StandAlone Test" finished-at="2023-12-20T14:48:29 IST" duration-ms="26815">
      <class name="shravang.Tests.StandAloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:02 IST" name="launchApplication" finished-at="2023-12-20T14:48:13 IST" duration-ms="11088" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:13 IST" name="submitOrder" data-provider="getData" finished-at="2023-12-20T14:48:14 IST" duration-ms="943" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pwd=Test@123, product=ZARA COAT 3, emailID=shravangundu231@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "product" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "product" is null
at shravang.pageobjects.ProductCatalog.addProductToCart(ProductCatalog.java:58)
at shravang.Tests.StandAloneTest.submitOrder(StandAloneTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:15 IST" name="tearDown" finished-at="2023-12-20T14:48:16 IST" duration-ms="1587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:16 IST" name="launchApplication" finished-at="2023-12-20T14:48:26 IST" duration-ms="9320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:26 IST" name="submitOrder" data-provider="getData" finished-at="2023-12-20T14:48:26 IST" duration-ms="674" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pwd=Test@123, product=ADIDAS ORIGINAL, emailID=shravangundu231@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "product" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "product" is null
at shravang.pageobjects.ProductCatalog.addProductToCart(ProductCatalog.java:58)
at shravang.Tests.StandAloneTest.submitOrder(StandAloneTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:27 IST" name="tearDown" finished-at="2023-12-20T14:48:29 IST" duration-ms="1910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:shravang.Tests.StandAloneTest@7d4f9aae]" started-at="2023-12-20T14:48:29 IST" name="OrderHistoryTest" finished-at="2023-12-20T14:48:29 IST" depends-on-methods="shravang.Tests.StandAloneTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method shravang.Tests.StandAloneTest.OrderHistoryTest() on instance shravang.Tests.StandAloneTest@7d4f9aae depends on not successfully finished methods 
[shravang.Tests.StandAloneTest.submitOrder() on instance shravang.Tests.StandAloneTest@7d4f9aae]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method shravang.Tests.StandAloneTest.OrderHistoryTest() on instance shravang.Tests.StandAloneTest@7d4f9aae depends on not successfully finished methods 
[shravang.Tests.StandAloneTest.submitOrder() on instance shravang.Tests.StandAloneTest@7d4f9aae]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- shravang.Tests.StandAloneTest -->
    </test> <!-- StandAlone Test -->
  </suite> <!-- Suite -->
</testng-results>
